# 03 - Multi-Trial Benchmarks (Champions & Classical Baselines)

This notebook consolidates the **Post-Evolution Benchmark Evaluation Pipeline** into a unified, reproducible workflow:
1. **Champion Extraction & Balance Check**: Selects top-performing candidate algorithms from the current SQLite database and exports `results/benchmark/champions.json`.
2. **Pre-Flight Diagnostic Audit**: Scans existing IOH traces in `results/ioh_traces/` and reports workload status.
3. **LLaMEA Champions Benchmark Execution**: Executes $N=20$ paired BBOB-instance trials per champion and reports clean objective gap ($\Delta y = f(x) - f^*$).
4. **Classical Baselines Benchmark Execution**: Executes the same $N=20$ instances for baseline optimizers (`CMA-ES`, `DE`, `PSO`).

The new protocol allows a **fixed 100,000 objective evaluations per trial** at every dimension, for champions and baselines. Synthesis targets 2D, 10D and 50D with the same allowance. The champion timeout remains 30 seconds.
**Storage warning:** configuration changes do not activate the separately prepared study. Complete the manual storage cutover before executing this notebook. Existing saved outputs describe the previous study, not new evaluations.
Results recorded under a different or unknown budget are marked for rerun, even with `force_rerun=false`; they are not resumed or counted as current completed coverage. Run both champion and baseline evaluation sections before refreshing analysis and figures.

The current schedule remains **instances 2–21**, with seed `42 + instance_id`; synthesis still uses instance 1. Multiple-instance synthesis is not implemented. Reuse requires matching budget, instance/seed identities and provenance, not just a completed run count. Restart the kernel before loading the updated settings.

In [3]:
# Setup paths and services
# Ensure project root src/ is in sys.path
import os
import sys
from pathlib import Path

cwd = Path('.').resolve()
root_dir = cwd.parent if cwd.name == 'notebooks' else cwd
src_dir = root_dir / 'src'
if str(src_dir) not in sys.path:
    sys.path.insert(0, str(src_dir))

import json
import pandas as pd
from IPython.display import display, HTML

from shared.config import RESULTS_DIR
from bootstrap.benchmark import build_benchmark_workflow

workflow = build_benchmark_workflow(root_dir)
sqlite_repo = workflow.sqlite_repo
champ_service = workflow.champion_selection
benchmark_service = workflow.service
CHAMPIONS_PATH = RESULTS_DIR / 'benchmark' / 'champions.json'

# Evaluation settings & matrix conditions loaded directly from configs/benchmark.toml

print('✅ Benchmark evaluation environment initialized.')

✅ Benchmark evaluation environment initialized.

## 1. Champion Selection & Experiment Balance Check
Query the current synthesis database, inspect run balance, and export problem-specific champions to `results/benchmark/champions.json`.

In [4]:
summary, total_completed = sqlite_repo.get_experiment_balance()

# Refresh the exported champion snapshot from the database currently loaded in this project.
champions_dict, df_champions = champ_service.export_champions(CHAMPIONS_PATH)
print(f'✅ Exported {len(df_champions)} champions to {CHAMPIONS_PATH}')

if summary.empty:
    raise RuntimeError('No completed experiments found in database. Please run Notebook 02 first.')

print(f'== Total Completed Experiments: {total_completed} ==')
print(summary.to_string(index=False))

# The snapshot above is refreshed before evaluation, so it always matches the active DB.

✅ Exported 1920 champions to /Users/nicolaibrahim/Desktop/proj/AAD_LLM/results/benchmark/champions.json
== Total Completed Experiments: 2160 ==
 problem_id  dim  noise_std     mode prompt_strategy                                    llm_name  completed_count
          1    2       0.00 explicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.00 explicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.00 explicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.00 explicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.00 explicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.00 explicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.00 explicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.00 explicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.00 explicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.00 explicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.00 explicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.00 explicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.00 implicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.00 implicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                5
          1    2       0.00 implicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.00 implicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.00 implicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.00 implicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.00 implicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.00 implicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.00 implicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.00 implicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.00 implicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.00 implicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.05 explicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.05 explicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.05 explicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.05 explicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.05 explicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.05 explicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.05 explicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.05 explicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                2
          1    2       0.05 explicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.05 explicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.05 explicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.05 explicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.05 implicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.05 implicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                2
          1    2       0.05 implicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.05 implicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.05 implicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.05 implicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.05 implicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.05 implicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.05 implicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.05 implicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.05 implicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.05 implicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.10 explicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.10 explicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.10 explicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.10 explicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.10 explicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.10 explicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.10 explicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.10 explicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.10 explicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.10 explicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.10 explicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                3
          1    2       0.10 explicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.10 implicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.10 implicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.10 implicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.10 implicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.10 implicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                3
          1    2       0.10 implicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.10 implicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.10 implicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.10 implicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.10 implicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.10 implicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.10 implicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.20 explicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.20 explicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.20 explicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.20 explicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.20 explicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.20 explicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.20 explicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.20 explicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.20 explicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.20 explicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.20 explicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                2
          1    2       0.20 explicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.20 implicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.20 implicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                2
          1    2       0.20 implicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.20 implicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.20 implicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                2
          1    2       0.20 implicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.20 implicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.20 implicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.20 implicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    2       0.20 implicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    2       0.20 implicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    2       0.20 implicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.00 explicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                2
          1    3       0.00 explicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                3
          1    3       0.00 explicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                3
          1    3       0.00 explicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.00 explicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.00 explicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.00 explicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.00 explicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                2
          1    3       0.00 explicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.00 explicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.00 explicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                2
          1    3       0.00 explicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.00 implicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.00 implicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.00 implicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.00 implicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.00 implicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.00 implicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.00 implicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.00 implicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.00 implicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.00 implicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.00 implicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.00 implicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                2
          1    3       0.05 explicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.05 explicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.05 explicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                2
          1    3       0.05 explicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.05 explicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                2
          1    3       0.05 explicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.05 explicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.05 explicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.05 explicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.05 explicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.05 explicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.05 explicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.05 implicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.05 implicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.05 implicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.05 implicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.05 implicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.05 implicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.05 implicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.05 implicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                2
          1    3       0.05 implicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.05 implicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.05 implicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.05 implicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.10 explicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.10 explicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.10 explicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.10 explicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                2
          1    3       0.10 explicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.10 explicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.10 explicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.10 explicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                2
          1    3       0.10 explicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.10 explicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.10 explicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.10 explicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.10 implicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.10 implicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.10 implicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.10 implicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.10 implicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                2
          1    3       0.10 implicit          guided      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.10 implicit        thinking DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.10 implicit        thinking      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.10 implicit        thinking      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.10 implicit   vectorization DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.10 implicit   vectorization      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1
          1    3       0.10 implicit   vectorization      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.20 explicit        baseline DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                2
          1    3       0.20 explicit        baseline      qwen2.5-coder-14b-instruct-q4_k_m.gguf                2
          1    3       0.20 explicit        baseline      qwen2.5-coder-32b-instruct-q4_k_m.gguf                1
          1    3       0.20 explicit          guided DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf                1
          1    3       0.20 explicit          guided      qwen2.5-coder-14b-instruct-q4_k_m.gguf                1

## 2. Pre-Flight Diagnostic Audit (Champions & Baselines Workload)
Audit pending vs. completed evaluation runs across all experimental conditions.

In [5]:
# 1. Load champions
with open(CHAMPIONS_PATH, "r", encoding="utf-8") as f:
    champions_raw = json.load(f)
champions_flat = benchmark_service.champion_selection.flatten_champions(champions_raw)

# ── Embedded HTML Dashboard Helper (Notebook-Local UI) ─────────────────────────
def render_html_dashboard(
    df_audit: pd.DataFrame,
    title: str = "Benchmark Evaluation Pre-Flight Audit",
    subtitle: str = "Real-time status of empirical evaluation runs",
    group_column: str = "model",
) -> str:
    """Render responsive HTML pre-flight dashboard for Jupyter display."""
    if df_audit.empty:
        return "<div>No audit data available.</div>"

    grp_col = (
        group_column
        if group_column in df_audit.columns
        else ("solver" if "solver" in df_audit.columns else df_audit.columns[0])
    )

    get_clean_model_label = benchmark_service.model_names.get_clean_model_label

    summary_rows = []
    for name, grp in df_audit.groupby(grp_col):
        clean_name = get_clean_model_label(str(name)) if grp_col == "model" else str(name).upper()
        total = len(grp)
        completed = len(grp[grp["status"] == "COMPLETED"])
        pending = len(grp[grp["status"] == "PENDING"])
        needs_rerun = len(grp[grp["status"] == "NEEDS_RERUN"])
        missing_code = len(grp[grp["status"] == "MISSING_CODE"])
        to_run_mask = grp["status"].isin(["PENDING", "NEEDS_RERUN"])
        if "is_filtered" in grp.columns:
            to_run_mask = to_run_mask & (~grp["is_filtered"])
        to_run = len(grp[to_run_mask])
        pct = (completed / total * 100) if total > 0 else 0.0
        summary_rows.append({
            "Group": clean_name,
            "Total Tasks": total,
            "Completed": completed,
            "Pending": pending,
            "Needs Rerun": needs_rerun,
            "Missing Code": missing_code,
            "Queue to Run": to_run,
            "Progress (%)": pct,
        })

    df_summary = pd.DataFrame(summary_rows)
    total_queue = int(df_summary["Queue to Run"].sum())
    total_completed = int(df_summary["Completed"].sum())
    total_tasks = int(df_summary["Total Tasks"].sum())
    overall_pct = (total_completed / total_tasks * 100) if total_tasks > 0 else 0.0

    html = f"""
<div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 950px; margin: 15px 0;">
    <div style="display: flex; align-items: center; justify-content: space-between; margin-bottom: 16px; border-bottom: 2px solid #E2E8F0; padding-bottom: 8px;">
        <div>
            <h2 style="margin: 0; color: #0F172A; font-size: 20px; font-weight: 700; display: flex; align-items: center; gap: 8px;">
                🚀 {title}
            </h2>
            <p style="margin: 4px 0 0 0; color: #64748B; font-size: 13px;">{subtitle}</p>
        </div>
        <div style="background: #EEF2F6; padding: 6px 12px; border-radius: 20px; font-size: 12px; font-weight: 600; color: #334155;">
            {total_tasks} Target Conditions
        </div>
    </div>

    <div style="display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 20px;">
        <div style="background: linear-gradient(135deg, #1E293B 0%, #0F172A 100%); padding: 14px 18px; border-radius: 10px; color: white; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
            <div style="font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #94A3B8;">Total Targets</div>
            <div style="font-size: 24px; font-weight: 700; color: #F8FAFC; margin-top: 4px;">{total_tasks}</div>
            <div style="font-size: 11px; color: #64748B; margin-top: 2px;">Across {len(df_summary)} Categories</div>
        </div>
        <div style="background: linear-gradient(135deg, #065F46 0%, #047857 100%); padding: 14px 18px; border-radius: 10px; color: white; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
            <div style="font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #A7F3D0;">Completed & Valid</div>
            <div style="font-size: 24px; font-weight: 700; color: #ECFDF5; margin-top: 4px;">{total_completed}</div>
            <div style="font-size: 11px; color: #D1FAE5; margin-top: 2px;">{overall_pct:.1f}% Overall Progress</div>
        </div>
        <div style="background: linear-gradient(135deg, #C2410C 0%, #9A3412 100%); padding: 14px 18px; border-radius: 10px; color: white; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
            <div style="font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #FED7AA;">Queue to Run</div>
            <div style="font-size: 24px; font-weight: 700; color: #FFF7ED; margin-top: 4px;">{total_queue}</div>
            <div style="font-size: 11px; color: #FFEDD5; margin-top: 2px;">Pending / Needs Rerun</div>
        </div>
        <div style="background: linear-gradient(135deg, #4338CA 0%, #3730A3 100%); padding: 14px 18px; border-radius: 10px; color: white; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
            <div style="font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #C7D2FE;">Overall Status</div>
            <div style="font-size: 24px; font-weight: 700; color: #EEF2FF; margin-top: 4px;">{overall_pct:.0f}%</div>
            <div style="font-size: 11px; color: #E0E7FF; margin-top: 2px;">Completion Rate</div>
        </div>
    </div>

    <div style="background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 10px; padding: 16px; margin-bottom: 8px;">
        <div style="font-size: 13px; font-weight: 700; color: #1E293B; margin-bottom: 12px; text-transform: uppercase; letter-spacing: 0.04em;">
            Completion Progress Breakdown
        </div>
"""
    for _, row in df_summary.iterrows():
        grp_name = row["Group"]
        tot = int(row["Total Tasks"])
        comp = int(row["Completed"])
        pend = int(row["Pending"])
        rerun = int(row["Needs Rerun"])
        q = int(row["Queue to Run"])
        pct = float(row["Progress (%)"])
        color = "#10B981" if pct > 75 else ("#3B82F6" if pct > 25 else "#F59E0B")
        rerun_pct = (rerun / tot * 100) if tot > 0 else 0

        html += f"""
        <div style="margin-bottom: 14px;">
            <div style="display: flex; justify-content: space-between; font-size: 13px; font-weight: 600; color: #334155; margin-bottom: 4px;">
                <span>⚙️ <strong style="color: #0F172A;">{grp_name}</strong> &nbsp;({comp}/{tot} Completed)</span>
                <span style="color: {color}; font-weight: 700;">{pct:.1f}%</span>
            </div>
            <div style="background: #E2E8F0; border-radius: 6px; height: 10px; overflow: hidden; display: flex;">
                <div style="background: #10B981; width: {pct}%; transition: width 0.3s;"></div>
                <div style="background: #EF4444; width: {rerun_pct}%;"></div>
            </div>
            <div style="display: flex; gap: 14px; font-size: 11px; color: #64748B; margin-top: 5px;">
                <span>✅ Completed: <strong style="color: #059669;">{comp}</strong></span>
                <span>⏳ Pending: <strong style="color: #D97706;">{pend}</strong></span>
                <span>⚠️ Needs Rerun: <strong style="color: #DC2626;">{rerun}</strong></span>
                <span>🎯 Queue: <strong style="color: #2563EB;">{q}</strong></span>
            </div>
        </div>
"""
    html += """
    </div>
</div>
"""
    return html

# 2. Audit champions workload (general overview by model)
df_champ_audit = benchmark_service.workload.audit_champions_workload()
print(f"🏆 Champions Workload: {len(df_champ_audit)} conditions ({df_champ_audit["status"].value_counts().to_dict()})")
display(HTML(render_html_dashboard(df_champ_audit, title="🏆 LLaMEA Champions Evaluation Audit", subtitle="Empirical benchmark evaluation status across LLM-evolved algorithms", group_column="model")))

# 3. Discover unique conditions for classical baselines (general overview by solver)
UNIQUE_CONFIGS = sorted(list({(c["dim"], c["noise_std"], c["problem_id"]) for c in champions_flat.values()}))
df_base_audit = benchmark_service.workload.audit_baselines_workload()
print(f"⚙️ Baselines Workload: {len(df_base_audit)} conditions ({df_base_audit["status"].value_counts().to_dict()})")
display(HTML(render_html_dashboard(df_base_audit, title="⚙️ Classical Baselines Evaluation Audit", subtitle="Empirical benchmark evaluation status across CMA-ES, DE, and PSO", group_column="solver")))

🏆 Champions Workload: 1920 conditions ({'PENDING': 1908, 'COMPLETED': 12})

⚙️ Baselines Workload: 240 conditions ({'PENDING': 240})

## 3. Execute LLaMEA Champions Benchmark (N=20 Independent Runs)
Evaluate evolved algorithms across target BBOB functions with full IOHprofiler `.dat` and `.json` logging.

In [6]:
results_champ_df = benchmark_service.run_champions()
print(f'✅ LLaMEA Champions evaluation complete: {len(results_champ_df)} conditions processed.')

================================================================================
🚀 STARTING BENCHMARK EVALUATIONS FOR CHAMPIONS
   1920 target conditions to evaluate
================================================================================

[1/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         2D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  📦 [CACHED] 20 runs found (Median Δy Error: 0.000). Skipping.

[2/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         2D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  📦 [CACHED] 20 runs found (Median Δy Error: 0.000). Skipping.

[3/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         2D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  📦 [CACHED] 20 runs found (Median Δy Error: 0.000). Skipping.

[4/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         2D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  📦 [CACHED] 20 runs found (Median Δy Error: 0.000). Skipping.

[5/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    baseline       Dim:         2D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  📦 [CACHED] 20 runs found (Median Δy Error: 0.001). Skipping.

[6/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    baseline       Dim:         2D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  📦 [CACHED] 20 runs found (Median Δy Error: 0.000). Skipping.

[7/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    baseline       Dim:         2D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  📦 [CACHED] 20 runs found (Median Δy Error: 0.000). Skipping.

[8/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    baseline       Dim:         2D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  📦 [CACHED] 20 runs found (Median Δy Error: 0.001). Skipping.

[9/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    guided         Dim:         2D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  📦 [CACHED] 20 runs found (Median Δy Error: 0.000). Skipping.

[10/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    guided         Dim:         2D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  📦 [CACHED] 20 runs found (Median Δy Error: 0.000). Skipping.

[11/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    guided         Dim:         2D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  📦 [CACHED] 20 runs found (Median Δy Error: 0.000). Skipping.

[12/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    guided         Dim:         2D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  📦 [CACHED] 20 runs found (Median Δy Error: 0.000). Skipping.

[13/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    guided         Dim:         2D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 20,000 | Time: 0.173s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[14/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    guided         Dim:         2D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.636 | Δy Error: 0.004 | Evals: 20,000 | Time: 0.443s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.001

[15/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    guided         Dim:         2D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 20,000 | Time: 0.278s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[16/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    guided         Dim:         2D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 20,000 | Time: 0.156s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[17/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    thinking       Dim:         2D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 20,000 | Time: 0.047s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[18/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    thinking       Dim:         2D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.628 | Δy Error: 0.012 | Evals: 20,000 | Time: 0.062s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.001

[19/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    thinking       Dim:         2D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.638 | Δy Error: 0.002 | Evals: 20,000 | Time: 0.626s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.010

[20/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    thinking       Dim:         2D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.638 | Δy Error: 0.002 | Evals: 20,000 | Time: 0.152s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.001

[21/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    thinking       Dim:         2D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.498 | Δy Error: 0.142 | Evals: 20,000 | Time: 0.195s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.054

[22/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    thinking       Dim:         2D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.562 | Δy Error: 0.078 | Evals: 200 | Time: 0.004s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.042

[23/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    thinking       Dim:         2D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 20,000 | Time: 0.059s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[24/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    thinking       Dim:         2D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -132.697 | Δy Error: 0.943 | Evals: 20,000 | Time: 0.409s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 4.165

[25/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    vectorization  Dim:         2D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.639 | Δy Error: 0.001 | Evals: 20,000 | Time: 0.347s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.002

[26/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    vectorization  Dim:         2D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.581 | Δy Error: 0.059 | Evals: 20,000 | Time: 0.525s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.019

[27/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    vectorization  Dim:         2D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -132.813 | Δy Error: 0.827 | Evals: 20,000 | Time: 0.132s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.220

[28/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    vectorization  Dim:         2D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -132.464 | Δy Error: 1.176 | Evals: 20,000 | Time: 0.102s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.404

[29/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    vectorization  Dim:         2D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 20,000 | Time: 0.175s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[30/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    vectorization  Dim:         2D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 20,000 | Time: 0.062s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[31/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    vectorization  Dim:         2D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.634 | Δy Error: 0.006 | Evals: 20,000 | Time: 0.057s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.002

[32/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    vectorization  Dim:         2D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.155 | Δy Error: 0.485 | Evals: 20,000 | Time: 0.060s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 3.672

[33/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         3D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.639 | Δy Error: 0.001 | Evals: 20,001 | Time: 0.144s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[34/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         3D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 30,000 | Time: 0.117s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.001

[35/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         3D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 30,000 | Time: 0.560s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[36/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         3D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.587 | Δy Error: 0.053 | Evals: 30,000 | Time: 0.083s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.026

[37/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    baseline       Dim:         3D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 30,000 | Time: 0.049s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[38/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    baseline       Dim:         3D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -130.187 | Δy Error: 3.453 | Evals: 30,000 | Time: 0.124s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[39/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    baseline       Dim:         3D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 30,000 | Time: 0.351s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[40/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    baseline       Dim:         3D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 30,000 | Time: 0.270s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[41/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    guided         Dim:         3D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 30,000 | Time: 0.244s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[42/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    guided         Dim:         3D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 30,000 | Time: 0.100s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[43/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    guided         Dim:         3D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 30,000 | Time: 0.572s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[44/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    guided         Dim:         3D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.108 | Δy Error: 0.532 | Evals: 30,000 | Time: 0.244s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.043

[45/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    guided         Dim:         3D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 30,000 | Time: 0.050s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[46/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    guided         Dim:         3D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 30,000 | Time: 0.357s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[47/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    guided         Dim:         3D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: 37.479 | Δy Error: 171.119 | Evals: 30,000 | Time: 0.171s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 134.779

[48/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    guided         Dim:         3D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 29,660 | Time: 0.459s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[49/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    thinking       Dim:         3D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...

<string>:29: UserWarning: [BUDGET OVERRUN] Problem evaluation called after budget exhausted (30000 >= 30000). Returning last observed fitness.
<string>:39: UserWarning: [BUDGET OVERRUN] Problem evaluation called after budget exhausted (30000 >= 30000). Returning last observed fitness.

  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.195 | Δy Error: 0.025 | Evals: 30,000 | Time: 0.152s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 5.814

[311/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    thinking       Dim:         3D     Noise level: σ=0.1     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 116.611 | Δy Error: 1.441 | Evals: 30,000 | Time: 0.489s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 2.537

[312/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    thinking       Dim:         3D     Noise level: σ=0.2     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.371 | Δy Error: 0.201 | Evals: 30,000 | Time: 0.139s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 1.735

[313/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    vectorization  Dim:         3D     Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.494 | Δy Error: 0.324 | Evals: 30,000 | Time: 0.051s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.371

[314/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    vectorization  Dim:         3D     Noise level: σ=0.05    Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.179 | Δy Error: 0.009 | Evals: 30,000 | Time: 0.450s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.011

[315/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    vectorization  Dim:         3D     Noise level: σ=0.1     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 125.418 | Δy Error: 10.248 | Evals: 30,000 | Time: 0.352s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 8.156

[316/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    vectorization  Dim:         3D     Noise level: σ=0.2     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.245 | Δy Error: 0.075 | Evals: 30,000 | Time: 0.104s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.663

[317/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    vectorization  Dim:         3D     Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 30,000 | Time: 0.308s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[318/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    vectorization  Dim:         3D     Noise level: σ=0.05    Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.179 | Δy Error: 0.009 | Evals: 30,000 | Time: 0.387s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 15.782

[319/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    vectorization  Dim:         3D     Noise level: σ=0.1     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 126.495 | Δy Error: 11.325 | Evals: 30,000 | Time: 0.340s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 4.688

[320/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    vectorization  Dim:         3D     Noise level: σ=0.2     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 118.357 | Δy Error: 3.187 | Evals: 30,000 | Time: 0.089s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 4.698

[321/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         5D     Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 50,000 | Time: 0.481s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[322/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         5D     Noise level: σ=0.05    Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 122.127 | Δy Error: 6.957 | Evals: 50,000 | Time: 0.424s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 14.668

[323/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         5D     Noise level: σ=0.1     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 29530.488 | Δy Error: 29415.318 | Evals: 50,000 | Time: 0.508s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 28106.234

[324/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         5D     Noise level: σ=0.2     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 13304.959 | Δy Error: 13189.789 | Evals: 50,000 | Time: 0.488s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 35155.679

[325/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    baseline       Dim:         5D     Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 127.792 | Δy Error: 12.622 | Evals: 50,000 | Time: 0.788s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 15.355

[326/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    baseline       Dim:         5D     Noise level: σ=0.05    Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 117.795 | Δy Error: 2.625 | Evals: 50,000 | Time: 0.996s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 13.041

[327/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    baseline       Dim:         5D     Noise level: σ=0.1     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 117.155 | Δy Error: 1.985 | Evals: 50,000 | Time: 0.223s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 12.671

[328/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    baseline       Dim:         5D     Noise level: σ=0.2     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.194 | Δy Error: 0.024 | Evals: 50,000 | Time: 0.581s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.017

[329/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    guided         Dim:         5D     Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 133.151 | Δy Error: 17.981 | Evals: 50,000 | Time: 0.509s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 26.913

[330/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    guided         Dim:         5D     Noise level: σ=0.05    Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 116.900 | Δy Error: 1.730 | Evals: 50,000 | Time: 0.157s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 4.573

[331/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    guided         Dim:         5D     Noise level: σ=0.1     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 50,000 | Time: 0.727s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.180

[332/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    guided         Dim:         5D     Noise level: σ=0.2     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 175.608 | Δy Error: 60.438 | Evals: 50,000 | Time: 0.192s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 38.817

[333/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    guided         Dim:         5D     Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.702 | Δy Error: 0.532 | Evals: 50,000 | Time: 0.435s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.861

[334/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    guided         Dim:         5D     Noise level: σ=0.05    Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 122.071 | Δy Error: 6.901 | Evals: 50,000 | Time: 0.491s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 6.688

[335/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    guided         Dim:         5D     Noise level: σ=0.1     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 172.907 | Δy Error: 57.737 | Evals: 50,000 | Time: 0.407s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 58.172

[336/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    guided         Dim:         5D     Noise level: σ=0.2     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 50,000 | Time: 0.407s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[337/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    thinking       Dim:         5D     Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.281 | Δy Error: 0.111 | Evals: 50,000 | Time: 0.088s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.175

[338/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    thinking       Dim:         5D     Noise level: σ=0.05    Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 144.575 | Δy Error: 29.405 | Evals: 50,000 | Time: 0.935s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 29.821

[339/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    thinking       Dim:         5D     Noise level: σ=0.1     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 124.033 | Δy Error: 8.863 | Evals: 50,000 | Time: 0.404s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 13.874

[340/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    thinking       Dim:         5D     Noise level: σ=0.2     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 159.460 | Δy Error: 44.290 | Evals: 50,000 | Time: 0.251s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 54.096

[341/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    thinking       Dim:         5D     Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.199 | Δy Error: 0.029 | Evals: 50,000 | Time: 0.128s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.022

[342/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    thinking       Dim:         5D     Noise level: σ=0.05    Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.936 | Δy Error: 0.766 | Evals: 50,000 | Time: 0.340s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 1.707

[343/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    thinking       Dim:         5D     Noise level: σ=0.1     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 140.838 | Δy Error: 25.668 | Evals: 50,000 | Time: 0.696s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 32.137

[344/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    thinking       Dim:         5D     Noise level: σ=0.2     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.491 | Δy Error: 0.321 | Evals: 50,000 | Time: 0.562s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 32.475

[345/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    vectorization  Dim:         5D     Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 149.285 | Δy Error: 34.115 | Evals: 50,000 | Time: 0.098s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 20.384

[346/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    vectorization  Dim:         5D     Noise level: σ=0.05    Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 138.631 | Δy Error: 23.461 | Evals: 50,000 | Time: 1.332s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 25.042

[347/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    vectorization  Dim:         5D     Noise level: σ=0.1     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 469.820 | Δy Error: 354.650 | Evals: 50,000 | Time: 0.698s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 363.313

[348/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    vectorization  Dim:         5D     Noise level: σ=0.2     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 125.680 | Δy Error: 10.510 | Evals: 50,000 | Time: 0.585s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 7.311

[349/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    vectorization  Dim:         5D     Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 137.413 | Δy Error: 22.243 | Evals: 36,072 | Time: 0.389s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 16.038

[350/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    vectorization  Dim:         5D     Noise level: σ=0.05    Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 50,000 | Time: 0.835s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[351/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    vectorization  Dim:         5D     Noise level: σ=0.1     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 50,000 | Time: 0.548s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[352/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        implicit   Strategy:    vectorization  Dim:         5D     Noise level: σ=0.2     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 50,000 | Time: 0.544s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[353/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         10D    Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 165.223 | Δy Error: 50.053 | Evals: 100,000 | Time: 0.285s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 60.188

[354/1920] 🏆 Champion: DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf
  Mode:        explicit   Strategy:    baseline       Dim:         10D    Noise level: σ=0.05    Problem:     f11 (Discus (f11))

## 4. Execute Classical Baselines Benchmark (CMA-ES, DE, PSO)
Run classical baseline optimizers across identical problem conditions for rigorous comparative benchmarking.

In [7]:
results_base_df = benchmark_service.run_baselines()
print(f'✅ Classical Baselines evaluation complete: {len(results_base_df)} conditions processed.')

================================================================================
🚀 STARTING BENCHMARK EVALUATIONS FOR BASELINES
   240 target conditions to evaluate
================================================================================

[1/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 426 | Time: 0.019s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[2/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0       Problem:     f8 (Rosenbrock (f8))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -44.640 | Best f: -44.640 | Δy Error: 0.000 | Evals: 552 | Time: 0.022s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[3/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 696 | Time: 0.028s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[4/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0       Problem:     f15 (Rastrigin Multi-Modal (f15))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 119.400 | Best f: 121.186 | Δy Error: 1.786 | Evals: 696 | Time: 0.028s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.995

[5/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0       Problem:     f21 (Gallagher 101 Peaks (f21))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -214.590 | Best f: -213.890 | Δy Error: 0.700 | Evals: 564 | Time: 0.022s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 1.074

[6/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 540 | Time: 0.023s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[7/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.05    Problem:     f8 (Rosenbrock (f8))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -44.640 | Best f: -44.640 | Δy Error: 0.000 | Evals: 948 | Time: 0.038s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[8/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.05    Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 570 | Time: 0.026s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[9/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.05    Problem:     f15 (Rastrigin Multi-Modal (f15))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 119.400 | Best f: 123.216 | Δy Error: 3.816 | Evals: 3,210 | Time: 0.159s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 2.007

[10/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.05    Problem:     f21 (Gallagher 101 Peaks (f21))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -214.590 | Best f: -214.590 | Δy Error: 0.000 | Evals: 552 | Time: 0.026s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.701

[11/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 480 | Time: 0.021s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[12/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.1     Problem:     f8 (Rosenbrock (f8))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -44.640 | Best f: -44.640 | Δy Error: 0.000 | Evals: 990 | Time: 0.041s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[13/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.1     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 732 | Time: 0.030s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 1.327

[14/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.1     Problem:     f15 (Rastrigin Multi-Modal (f15))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 119.400 | Best f: 119.400 | Δy Error: 0.000 | Evals: 600 | Time: 0.026s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 1.010

[15/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.1     Problem:     f21 (Gallagher 101 Peaks (f21))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -214.590 | Best f: -213.447 | Δy Error: 1.143 | Evals: 3,210 | Time: 0.142s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 1.049

[16/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 522 | Time: 0.022s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[17/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.2     Problem:     f8 (Rosenbrock (f8))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -44.640 | Best f: -42.634 | Δy Error: 2.006 | Evals: 3,210 | Time: 0.124s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.112

[18/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.2     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 696 | Time: 0.029s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 4.044

[19/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.2     Problem:     f15 (Rastrigin Multi-Modal (f15))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 119.400 | Best f: 119.400 | Δy Error: 0.000 | Evals: 516 | Time: 0.022s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 2.022

[20/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         2D     Noise level: σ=0.2     Problem:     f21 (Gallagher 101 Peaks (f21))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -214.590 | Best f: -212.576 | Δy Error: 2.014 | Evals: 3,210 | Time: 0.138s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 1.181

[21/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 749 | Time: 0.034s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[22/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0       Problem:     f8 (Rosenbrock (f8))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -44.640 | Best f: -44.640 | Δy Error: 0.000 | Evals: 1,134 | Time: 0.041s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[23/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 987 | Time: 0.036s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[24/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0       Problem:     f15 (Rastrigin Multi-Modal (f15))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 119.400 | Best f: 121.390 | Δy Error: 1.990 | Evals: 980 | Time: 0.043s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 2.026

[25/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0       Problem:     f21 (Gallagher 101 Peaks (f21))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -214.590 | Best f: -212.334 | Δy Error: 2.256 | Evals: 742 | Time: 0.029s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 1.632

[26/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 728 | Time: 0.030s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[27/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.05    Problem:     f8 (Rosenbrock (f8))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -44.640 | Best f: -44.640 | Δy Error: 0.000 | Evals: 1,155 | Time: 0.043s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[28/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.05    Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 945 | Time: 0.035s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[29/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.05    Problem:     f15 (Rastrigin Multi-Modal (f15))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 119.400 | Best f: 123.447 | Δy Error: 4.047 | Evals: 4,060 | Time: 0.163s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 2.035

[30/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.05    Problem:     f21 (Gallagher 101 Peaks (f21))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -214.590 | Best f: -213.895 | Δy Error: 0.695 | Evals: 4,060 | Time: 0.151s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 1.099

[31/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.1     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 805 | Time: 0.031s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[32/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.1     Problem:     f8 (Rosenbrock (f8))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -44.640 | Best f: -44.640 | Δy Error: 0.000 | Evals: 1,267 | Time: 0.055s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.040

[33/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.1     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 1,309 | Time: 0.058s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[34/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.1     Problem:     f15 (Rastrigin Multi-Modal (f15))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 119.400 | Best f: 124.402 | Δy Error: 5.002 | Evals: 4,060 | Time: 0.162s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 3.104

[35/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.1     Problem:     f21 (Gallagher 101 Peaks (f21))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -214.590 | Best f: -203.548 | Δy Error: 11.042 | Evals: 4,060 | Time: 0.162s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 1.150

[36/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.2     Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 910 | Time: 0.038s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[37/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.2     Problem:     f8 (Rosenbrock (f8))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -44.640 | Best f: -44.640 | Δy Error: 0.000 | Evals: 819 | Time: 0.030s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 1.097

[38/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.2     Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 126.261 | Δy Error: 11.091 | Evals: 4,760 | Time: 0.192s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 1.747

[39/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.2     Problem:     f15 (Rastrigin Multi-Modal (f15))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 119.400 | Best f: 121.525 | Δy Error: 2.125 | Evals: 4,060 | Time: 0.159s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 2.890

[40/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         3D     Noise level: σ=0.2     Problem:     f21 (Gallagher 101 Peaks (f21))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -214.590 | Best f: -212.175 | Δy Error: 2.415 | Evals: 3,850 | Time: 0.146s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 1.823

[41/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         5D     Noise level: σ=0       Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 1,312 | Time: 0.050s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[42/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         5D     Noise level: σ=0       Problem:     f8 (Rosenbrock (f8))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -44.640 | Best f: -44.640 | Δy Error: 0.000 | Evals: 2,616 | Time: 0.087s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[43/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         5D     Noise level: σ=0       Problem:     f11 (Discus (f11))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 115.170 | Best f: 115.170 | Δy Error: 0.000 | Evals: 1,800 | Time: 0.074s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[44/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         5D     Noise level: σ=0       Problem:     f15 (Rastrigin Multi-Modal (f15))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: 119.400 | Best f: 129.350 | Δy Error: 9.950 | Evals: 1,784 | Time: 0.066s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 7.960

[45/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         5D     Noise level: σ=0       Problem:     f21 (Gallagher 101 Peaks (f21))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -214.590 | Best f: -212.117 | Δy Error: 2.473 | Evals: 1,176 | Time: 0.043s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 2.128

[46/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         5D     Noise level: σ=0.05    Problem:     f1 (Sphere (f1))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -133.640 | Best f: -133.640 | Δy Error: 0.000 | Evals: 1,360 | Time: 0.052s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 0.000

[47/240] ⚙️ Baseline: CMA-ES
  Mode:        —          Strategy:    —              Dim:         5D     Noise level: σ=0.05    Problem:     f8 (Rosenbrock (f8))
  🔄 [RESUMING] Found 19/20 completed runs. Continuing from Trial 20...
  • ⚡ Trial 20/20 | Instance: 21 | Seed: 63 | f-opt: -44.640 | Best f: -39.969 | Δy Error: 4.671 | Evals: 4,040 | Time: 0.139s
  ✨ [COMPLETED] 20 runs finished | Median Δy Error: 2.832


## Separate robustness and generalization campaigns

Noise robustness freezes a clean champion and varies noise on its original function.
Cross-function generalization freezes a clean, explicit, baseline-strategy champion
and changes only the target function at the original dimension. These are secondary
analyses, not part of the native champion ranking. Trials use instances 2–21,
excluding synthesis instance 1. Previously inspected instances 2–20 are not a new untouched test set.
Enable cross-function evaluation in `configs/benchmark.toml` before running it.
The switches below deliberately default to audit-only: no extra campaign runs on
notebook execution unless explicitly requested.

In [8]:
RUN_NOISE_ROBUSTNESS = False
RUN_CROSS_FUNCTION = False

noise_audit = benchmark_service.workload.audit_noise_robustness_workload()
transfer_audit = benchmark_service.workload.audit_cross_function_workload()
print(f"Noise robustness: {len(noise_audit)} conditions")
print(f"Cross-function generalization: {len(transfer_audit)} conditions (opt-in)")
display(noise_audit)
display(transfer_audit)

if RUN_NOISE_ROBUSTNESS:
    noise_results = benchmark_service.run_noise_robustness()
if RUN_CROSS_FUNCTION:
    if not benchmark_service.config.cross_function_enabled:
        raise ValueError("Enable benchmarking.cross_function_enabled in benchmark.toml first.")
    transfer_results = benchmark_service.run_cross_function_benchmarks()

# Always export the current readiness matrix, without treating missing trials as failures.
from shared.config import RESULTS_DIR
transfer_report_dir = RESULTS_DIR / "reports"
transfer_report_dir.mkdir(parents=True, exist_ok=True)
benchmark_service.workload.audit_noise_robustness_workload().to_csv(
    transfer_report_dir / "noise_robustness_readiness_v1.csv", index=False
)
benchmark_service.workload.audit_cross_function_workload().to_csv(
    transfer_report_dir / "cross_function_readiness_v1.csv", index=False
)

Noise robustness: 720 conditions
Cross-function generalization: 0 conditions (opt-in)

,key,raw_key,solver_type,solver,display_name,model,strategy,problem_id,source_problem_id,source_noise_std,...,dim,noise_std,mode,target_runs,runs_found,recorded_trials,reason,status,median_error,is_filtered
0,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf/f1...,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf/f1...,noise_robustness,deepseek_coder_v2_lite_instruct_q4_k_m_baseline,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf (n...,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf,baseline,1,1,0.0,...,2,0.05,explicit,20,0,0,missing_provenance,PENDING,None,False
1,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf/f1...,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf/f1...,noise_robustness,deepseek_coder_v2_lite_instruct_q4_k_m_baseline,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf (n...,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf,baseline,1,1,0.0,...,2,0.10,explicit,20,0,0,missing_provenance,PENDING,None,False
2,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf/f1...,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf/f1...,noise_robustness,deepseek_coder_v2_lite_instruct_q4_k_m_baseline,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf (n...,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf,baseline,1,1,0.0,...,2,0.20,explicit,20,0,0,missing_provenance,PENDING,None,False
3,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf/f1...,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf/f1...,noise_robustness,deepseek_coder_v2_lite_instruct_q4_k_m_guided,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf (n...,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf,guided,1,1,0.0,...,2,0.05,explicit,20,0,0,missing_provenance,PENDING,None,False
4,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf/f1...,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf/f1...,noise_robustness,deepseek_coder_v2_lite_instruct_q4_k_m_guided,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf (n...,DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf,guided,1,1,0.0,...,2,0.10,explicit,20,0,0,missing_provenance,PENDING,None,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,qwen2.5-coder-32b-instruct-q4_k_m.gguf/f21_10D...,qwen2.5-coder-32b-instruct-q4_k_m.gguf/f21_10D...,noise_robustness,qwen_32b_thinking,qwen2.5-coder-32b-instruct-q4_k_m.gguf (noise ...,qwen2.5-coder-32b-instruct-q4_k_m.gguf,thinking,21,21,0.0,...,10,0.10,explicit,20,0,0,missing_provenance,PENDING,None,False
716,qwen2.5-coder-32b-instruct-q4_k_m.gguf/f21_10D...,qwen2.5-coder-32b-instruct-q4_k_m.gguf/f21_10D...,noise_robustness,qwen_32b_thinking,qwen2.5-coder-32b-instruct-q4_k_m.gguf (noise ...,qwen2.5-coder-32b-instruct-q4_k_m.gguf,thinking,21,21,0.0,...,10,0.20,explicit,20,0,0,missing_provenance,PENDING,None,False
717,qwen2.5-coder-32b-instruct-q4_k_m.gguf/f21_10D...,qwen2.5-coder-32b-instruct-q4_k_m.gguf/f21_10D...,noise_robustness,qwen_32b_vectorization,qwen2.5-coder-32b-instruct-q4_k_m.gguf (noise ...,qwen2.5-coder-32b-instruct-q4_k_m.gguf,vectorization,21,21,0.0,...,10,0.05,explicit,20,0,0,missing_provenance,PENDING,None,False
718,qwen2.5-coder-32b-instruct-q4_k_m.gguf/f21_10D...,qwen2.5-coder-32b-instruct-q4_k_m.gguf/f21_10D...,noise_robustness,qwen_32b_vectorization,qwen2.5-coder-32b-instruct-q4_k_m.gguf (noise ...,qwen2.5-coder-32b-instruct-q4_k_m.gguf,vectorization,21,21,0.0,...,10,0.10,explicit,20,0,0,missing_provenance,PENDING,None,False
719,qwen2.5-coder-32b-instruct-q4_k_m.gguf/f21_10D...,qwen2.5-coder-32b-instruct-q4_k_m.gguf/f21_10D...,noise_robustness,qwen_32b_vectorization,qwen2.5-coder-32b-instruct-q4_k_m.gguf (noise ...,qwen2.5-coder-32b-instruct-q4_k_m.gguf,vectorization,21,21,0.0,...,10,0.20,explicit,20,0,0,missing_provenance,PENDING,None,False

Empty DataFrame
Columns: []
Index: []

## 5. Post-evaluation outcome summary and synthesis review

Read-only summary of current native champions and baselines. This does not run experiments, change results or write reports. Historical unexecuted tails are excluded. Valid trials exclude execution failures; execution and failure rates use executed trials as their denominator. Target success rate counts trials reaching the primary error target, including failures in its denominator. The overall median includes failures, while the median finite error describes only successful executions. Missing/stale and incomplete conditions require benchmark completion before synthesis decisions. `all_failed` and `mostly_failed` (>50% execution failures) are review candidates, not automatic reruns. Median error above the configured secondary target is a performance flag, not proof of a bug. The full tables remain available as `evaluation_summary`, `failure_review` and `large_error_review`.

In [9]:
evaluation_summary = benchmark_service.summarize_results()
if evaluation_summary.empty:
    print("No current benchmark conditions to summarize.")
else:
    print(f"Summary of {len(evaluation_summary)} conditions; primary target={benchmark_service.config.reliability.primary_target:g}, secondary target={benchmark_service.config.reliability.secondary_target:g}")
    display(pd.crosstab(evaluation_summary["Model"], evaluation_summary["Category"]))
    review_columns = ["Model", "Experiment ID", "Algorithm", "Mode", "Strategy", "Problem ID", "Dim", "Noise", "Executed trials", "Valid trials", "Expected trials", "Failed trials", "Execution rate", "Failure rate", "Solved trials", "Primary target rate", "Median error", "Median finite error", "Best baseline median error", "Category", "Suggested action"]
    failure_review = evaluation_summary[evaluation_summary["Category"].isin(["all_failed", "mostly_failed", "some_failed", "incomplete", "missing_or_stale"])][review_columns]
    large_error_review = evaluation_summary[evaluation_summary["Category"] == "large_error"][review_columns]
    formats = {"Execution rate": "{:.1%}", "Failure rate": "{:.1%}", "Primary target rate": "{:.1%}", "Noise": "{:g}", "Median error": "{:.3f}", "Median finite error": "{:.3f}", "Best baseline median error": "{:.3f}"}
    print(f"Failure/readiness review: {len(failure_review)} conditions (first 100 shown).")
    display(failure_review.head(100).style.format(formats, na_rep="—"))
    print(f"Large finite-error review: {len(large_error_review)} conditions (first 50 shown; compare with baselines before rerunning).")
    display(large_error_review.head(50).style.format(formats, na_rep="—"))
    print("Suggested experiment IDs to REVIEW for fresh synthesis, grouped by owning LLM:")
    for model, group in evaluation_summary[evaluation_summary["Rerun candidate"]].groupby("Model", sort=True):
        print(f"{model}: {sorted(group["Experiment ID"].dropna().astype(int).unique().tolist())}")
    print("No reruns launched. Review diagnostics first; explicitly select IDs in Notebook 02/configuration.")

Summary of 2160 conditions; primary target=1e-08, secondary target=0.01

Category,finite_results,large_error,mostly_failed,some_failed
Model,,,,
DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf,238,389,4,9
cmaes,31,49,0,0
de,18,62,0,0
pso,32,48,0,0
qwen2.5-coder-14b-instruct-q4_k_m.gguf,216,402,6,16
qwen2.5-coder-32b-instruct-q4_k_m.gguf,255,370,2,13

Failure/readiness review: 50 conditions (first 100 shown).

Large finite-error review: 1320 conditions (first 50 shown; compare with baselines before rerunning).

Suggested experiment IDs to REVIEW for fresh synthesis, grouped by owning LLM:
DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf: [2139, 2322, 2360, 2657]
qwen2.5-coder-14b-instruct-q4_k_m.gguf: [49, 177, 268, 327, 331, 416]
qwen2.5-coder-32b-instruct-q4_k_m.gguf: [1028, 1132]
No reruns launched. Review diagnostics first; explicitly select IDs in Notebook 02/configuration.